AWSTemplateFormatVersion: 2010-09-09
Description: 'This template creates some Alarms and Scaling Policies to manage an AutoScaling Group'

Resources:

  #https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/quickref-autoscaling.html#scenario-as-policy
  ScaleUpPolicy:
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-policy.html
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AdjustmentType: ChangeInCapacity
      AutoScalingGroupName: !ImportValue WordpressAutoscalingGroup
      Cooldown: '1'
      ScalingAdjustment: '1'

  ScaleDownPolicy:
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-policy.html
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AdjustmentType: ChangeInCapacity
      AutoScalingGroupName: !ImportValue WordpressAutoscalingGroup
      Cooldown: '1'
      ScalingAdjustment: '-1'

  CPUAlarmHigh:
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cw-alarm.html
    Type: AWS::CloudWatch::Alarm
    Properties:
      EvaluationPeriods: '1'
      Statistic: Average
      Threshold: '75'
      AlarmDescription: Alarm if CPU too high
      Period: '60'
      AlarmActions:
        - !Ref ScaleUpPolicy
      Namespace: AWS/EC2
      Dimensions:
        - Name: AutoScalingGroupName
          Value: !ImportValue WordpressAutoscalingGroup
      ComparisonOperator: GreaterThanThreshold
      MetricName: CPUUtilization

  CPUAlarmLow:
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cw-alarm.html
    Type: AWS::CloudWatch::Alarm
    Properties:
      EvaluationPeriods: '1'
      Statistic: Average
      Threshold: '25'
      AlarmDescription: Alarm if CPU too low
      Period: '60'
      AlarmActions:
        - !Ref ScaleDownPolicy
      Namespace: AWS/EC2
      Dimensions: # The dimensions seem to tie the Alarm to the Resource to monitor, and the Name seems to be a specific key for the type of Resource
        - Name: AutoScalingGroupName
          Value: !ImportValue WordpressAutoscalingGroup
      ComparisonOperator: LessThanThreshold
      MetricName: CPUUtilization

