AWSTemplateFormatVersion: 2010-09-09
Description: 'This template builds a basic linux EC2 container instance that connects to an ECS cluster.'

Parameters:
  KeyNameParam:
    Description: EC2 Instance SSH Key
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair.

  InstanceTypeParam:
    Description: EC2 instance specs configuration
    Type: String
    Default: t2.micro
    AllowedValues:
    - t2.micro
    - t2.small
    - t2.medium

Mappings:
  AMIs:
    eu-west-1:
      Name: ami-9cbe9be5

Resources:

  EC2Instance:
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html
  # Attaching IAM roles to EC2 -> https://hackernoon.com/attach-an-iam-role-to-an-ec2-instance-with-cloudformation-33c517a8d4c3
  # Installing the ECS Container Agent -> https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-agent-install.html
  # Launching an EC2 instance into an ECS Cluster -> https://docs.aws.amazon.com/AmazonECS/latest/developerguide/launch_container_instance.html
    Type: "AWS::EC2::Instance"
    Metadata:
      Comment: Install a Docker Server
      AWS::CloudFormation::Init:
        config:
          packages:
            yum:
              docker: []
              ecs-init: []
          files:
            "/etc/cfn/cfn-hup.conf":
              content: !Sub |
                [main]
                stack=${AWS::StackId}
                region=${AWS::Region}
              mode: "000400"
              owner: "root"
              group: "root"
            "/etc/cfn/hooks.d/cfn-auto-reloader.conf":
              content: !Sub |
                [cfn-auto-reloader-hook]
                triggers=post.update
                path=Resources.WebServerHost.Metadata.AWS::CloudFormation::Init
                action=/opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource WebServerHost --region ${AWS::Region}
          commands:
            docker-permissions:            
              command: usermod -a -G docker ec2-user
              cwd: /
          services:
            sysvinit:
              docker:
                enabled: 'true'
                ensureRunning: 'true'
              ecs:
                enabled: 'true'
                ensureRunning: 'true'
    CreationPolicy:
      ResourceSignal:
        Timeout: PT5M
    Properties: 
      IamInstanceProfile: !ImportValue IAMInstanceProfileEC2ContainerInstanceOut
      ImageId: !FindInMap [ AMIs, !Ref 'AWS::Region', Name]
      InstanceType: !Ref InstanceTypeParam
      KeyName: !Ref KeyNameParam
      SecurityGroupIds: 
        - !ImportValue EC2SecurityGroupSSHGroupIdOut
        - !ImportValue EC2SecurityGroupHTTPGroupIdOut
      SubnetId: !ImportValue EC2Subnet1Out
      Tags:
        - Key: Name
          Value: EC2ContainerInstance
      UserData:
        "Fn::Base64":
          !Sub |
            #!/bin/bash
            yum update -y
            # cfn-init handling
            # Get the latest CloudFormation package
            yum update -y aws-cfn-bootstrap
            # Start cfn-init
            echo "/opt/aws/bin/cfn-init -s ${AWS::StackId} -r EC2Instance --region=${AWS::Region} -v"
            /opt/aws/bin/cfn-init -s ${AWS::StackId} -r EC2Instance --region=${AWS::Region} -v
            # Start up the cfn-hup daemon to listen for changes to the EC2 instance metadata
            /opt/aws/bin/cfn-hup
            # All done so signal success
            /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackId} --resource EC2Instance --region=${AWS::Region}
            # Download and execute ECR login command (url for fix at the start of resource)
            eval $(aws ecr get-login --no-include-email --region eu-west-1 | sed 's|https://||')
            # Connect into the ECS Cluster with the name defined in ECSCluster.yaml
            echo ECS_CLUSTER=ecs-cluster >> /etc/ecs/ecs.config





