AWSTemplateFormatVersion: 2010-09-09
Description: 'This template builds an ECS Cluster.'

Resources:

  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-cluster.html
  ECSCluster:
    Type: "AWS::ECS::Cluster"
    Properties:
      ClusterName: ecs-cluster
