version: "3"
services:
  web:
    image: 963697544248.dkr.ecr.eu-west-1.amazonaws.com/docker-get-started:ecs-demo
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
    networks:
      - webnet
networks:
  webnet:
